apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: existing
  namespace: default
spec:
  handle: mgmt
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: ansible-home-sample
  namespace: default
spec:
  url: https://github.com/zreigz/ansible-home.git
---
apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: ansible-home-sample
  namespace: default
spec:
  name: "ansible-home-sample"
  detach: true
  type: ANSIBLE
  configuration:
    version: "sha-6033479-ansible-11.0"
    image: "ghcr.io/pluralsh/harness"
    ansible:
      playbook: "/plural/main.yaml"
      inventory: "/plural/hosts.ini"
      privateKeyFile: "/tmp/ssh-privatekey"
  repositoryRef:
    name: ansible-home-sample
    namespace: default
  clusterRef:
    name: existing
    namespace: default
  git:
    ref: main
    folder: /
  files:
    - mountPath: /tmp
      secretRef:
        name: ssh-key-secret